# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotwire_turbo_frame_hovercards_development

test:
  <<: *default
  database: hotwire_turbo_frame_hovercards_test

production:
  <<: *default
  database: hotwire_turbo_frame_hovercards_production
  username: hotwire_turbo_frame_hovercards
  password: <%= ENV["HOTWIRE_TURBO_FRAME_HOVERCARDS_DATABASE_PASSWORD"] %>
